import { wrapWithBanner } from './common.js';
import type { Renderer } from './compose.js';
import { composeAttributionSection, filterSections } from './compose.js';
import type { AgentPolicyConfig } from '../config/types.js';

const PREAMBLE =
  'This file is a concise mirror for Claude. The canonical, authoritative policy lives in `AGENTS.md`. Do not edit this file by hand — edit `agent-policy.yaml` and run `agent-policy sync`.';

function renderBody(config: AgentPolicyConfig): string {
  const parts: string[] = [];
  const name = config.project?.name ?? 'Project';
  parts.push(`# ${name}`);
  if (config.project?.description) parts.push('', config.project.description);
  parts.push('', PREAMBLE, '');

  const concise = config.renderers?.claude_md?.concise ?? false;
  const sections = filterSections(config.policy?.sections ?? [], 'claude_md', concise);
  for (const s of sections) {
    parts.push(`## ${s.title}`, '', s.body.trim(), '');
  }

  const attribution = composeAttributionSection(config);
  if (attribution) parts.push(attribution, '');
  return parts.join('\n');
}

export const claudeMdRenderer: Renderer = {
  id: 'claude_md',
  defaultPath: 'CLAUDE.md',
  render(config) {
    return wrapWithBanner(renderBody(config));
  },
};
