import { createHash } from 'node:crypto';

export const BANNER_FIRST_LINE =
  '<!-- Generated by agent-policy. Do not edit directly. Edit agent-policy.yaml instead. -->';

export function bodyHash(body: string): string {
  return createHash('sha256').update(body, 'utf8').digest('hex').slice(0, 16);
}

export function wrapWithBanner(body: string): string {
  const normalized = body.endsWith('\n') ? body : body + '\n';
  const hash = bodyHash(normalized);
  return `${BANNER_FIRST_LINE}\n<!-- agent-policy:hash=${hash} -->\n\n${normalized}`;
}

export function stripBanner(content: string): { body: string; hash: string | null } {
  const lines = content.split('\n');
  if (lines[0] !== BANNER_FIRST_LINE) {
    return { body: content, hash: null };
  }
  const hashLine = lines[1] ?? '';
  const match = hashLine.match(/agent-policy:hash=([a-f0-9]+)/);
  const hash = match && match[1] ? match[1] : null;
  // Layout: [banner, hashLine, '', ...body]
  const rest = lines.slice(2);
  if (rest[0] === '') rest.shift();
  const body = rest.join('\n');
  return { body, hash };
}
